
package com.shu.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Function", targetNamespace = "http://com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Function {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transWords", targetNamespace = "http://com/", className = "com.shu.service.TransWords")
    @ResponseWrapper(localName = "transWordsResponse", targetNamespace = "http://com/", className = "com.shu.service.TransWordsResponse")
    public String transWords(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
